### ISSUE TITLE
circular detector

### ISSUE THREAD

**Issue by eddymaoui** [McStasMcXtrace/Schools#12]
hi 
I need a semi circular detector for my project 
how and where i can find it ?
thanks

**Comment by ebknudsen** [comment]
Hi,
On a general note: the command **mcdoc**, opens a web-page in your browser with a list of all available McStas-components. Or from the GUI: **Help->mcdoc Component Reference** does the same.

To your question:
It depends on what you mean by semi-circular. If you mean a true flat plane half-circle monitor, you could use Monitor_nD with "radius" in the option string in conjunction with a guard slit in front of it to cover it's one half.
If on the other hand you mean a cylindrical monitor which only covers half of the angular range (say from 0 to 180 degrees), you could use the "banana" option to Monitor_nD.

cheers
Erik

**Comment by willend** [comment]
I agree @ebknudsen. I have a feeling the information @eddymaoui is after is now provided in https://github.com/McStasMcXtrace/McCode/issues/792. - Hence closing here as this can be considered a duplicate.
